name: Build

on: [push]

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/checkout@v2
        with:
          repository: vitasdk/vdpm
          path: vdpm
      - name: Install VitaSDK
        run: |
          cd $WORKSPACE_VDPM
          ./bootstrap-vitasdk.sh
          export VITASDK=/usr/local/vitasdk
          export PATH=$VITASDK/bin:$PATH
          ./install-all.sh
        env:
          WORKSPACE_VDPM: ${{ github.workspace }}/vdpm
      - name: Make project
        run: |
          cd $WORKSPACE_MAIN
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..;
          make
        env:
          WORKSPACE_MAIN: ${{ github.workspace }}/main
