name: Build

on: [push]

jobs:
  myjob:
    runs-on: ubuntu-latest
    services:
      vitasdk:
        image: gnuton/vitasdk-docker
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/checkout@v2
        with:
          path: vdpm
      - run: |
          ls $workspace/main
          ls $workspace/vdpm
        env:
          workspace: ${{ github.workspace }}
