name: Build

on: [push]

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://gnuton/vitasdk-docker:latest
      - run: "export DOCKER_NAME=$(docker ps -l --format {{.Names}})"
      - run: 'echo "${DOCKER_NAME}"'
