name: Build

on: [push]

jobs:
  myjob:
    runs-on: ubuntu-latest
    services:
      vitasdk:
        image: gnuton/vitasdk-docker
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..;
          make
